### ISSUE TITLE
Fields and context not working for latest release 1.6.2 and even 1.6.1

### ISSUE THREAD

**Issue by palakagrawal22** [imryche/blockkit#106] opened 2024-01-03 05:39 UTC
still the fields are not working error is : The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/view]', '[ERROR] failed to match all allowed schemas [json-pointer:/view/blocks/4/fields/0]', '[ERROR] must provide an object [json-pointer:/view/blocks/4/fields/0]', '[ERROR] must provide an object [json-pointer:/view/blocks/4/fields/0]', '[ERROR] failed to match all allowed schemas [json-pointer:/view/blocks/4/fields/1]', '[ERROR] must provide an object [json-pointer:/view/blocks/4/fields/1]', '[ERROR] must provide an object [json-pointer:/view/blocks/4/fields/1]', '[ERROR] failed to match all allowed schemas [json-pointer:/view/blocks/5/fields/0]', '[ERROR] must provide an object [json-pointer:/view/blocks/5/fields/0]', '[ERROR] must provide an object [json-pointer:/view/blocks/5/fields/0]', '[ERROR] failed to match all allowed schemas [json-pointer:/view/blocks/5/fields/1]', '[ERROR] must provide an object [json-pointer:/view/blocks/5/fields/1]', '[ERROR] must provide an object [json-pointer:/view/blocks/5/fields/1]']}}

**Comment by imryche** [comment] 2024-01-03 12:12
It would be great if you could provide the code you used to generate the UI.

**Comment by palakagrawal22** [comment] 2024-01-03 13:35
def severity_update(channel_id, channel_name, optionlist):
    sev_choices_block = Input(
            element=StaticSelect(
                    placeholder="Select an item",
                    options=[
                        PlainOption(text="Severity - 0", value="Severity - 0"),
                        PlainOption(text="Severity - 1", value="Severity - 1"),
                        PlainOption(text="Severity - 2", value="Severity - 2"),
                        PlainOption(text="Severity - 3", value="Severity - 3"),
                        ],
                    action_id="action_severity",
                    ),
            label="Severity",
            block_id="block_severity",
            )
    sev_change_reason_block = Input(
            block_id="block_sev_change_reason",
            element=PlainTextInput(multiline=True, action_id="action_sev_change", max_length=255),
            label="Severity Change Reason",
            )
    divider_block = Divider()
    all_blocks = {'divider': divider_block, 'severities': sev_choices_block,
                  'sev_change_reason': sev_change_reason_block}
    payload = Modal(
            title="Update Incident Severity",
            submit="Submit",
            callback_id="incident_sev_update",
            private_metadata=f"channel_id={channel_id},channel_name={channel_name}",
            close="Cancel",
            blocks=[all_blocks['divider']]
            )
    itr_block = []
    itr_name = list(optionlist.keys())
    for count in range(int(len(optionlist))):
        inival = optionlist[itr_name[count]]
        itrname = itr_name[count]
        itr_block.append(
                Section(
                        fields=[itrname, inival]
                        ),
                )
    itr_title = Section(
            fields=["ITRs:", "Current severity"]
            )
    payload.blocks.insert(len(payload.blocks), all_blocks['severities'])
    payload.blocks.insert(len(payload.blocks), all_blocks['sev_change_reason'])
    payload.blocks.insert(len(payload.blocks), itr_title)
    for block in itr_block:
        payload.blocks.insert(len(payload.blocks), block)
    note = Section(
            text=f'Note: Change in ITR will be reflected after submission of form'
            )
    payload.blocks.insert(len(payload.blocks), note)
    payload = payload.build()
    return payload

**Comment by palakagrawal22** [comment] 2024-01-03 13:35
its working for previous version 1.5.2

**Comment by imryche** [comment] 2024-01-03 15:40
Can you please provide the output of the `.build()` method call, so I can investigate further?

**Comment by palakagrawal22** [comment] 2024-01-03 15:43
payload = Message(
    blocks=[
        Input(
            element=PlainTextInput(action_id="plain_text_input-action"), label="Label"
        ),
        Section(fields=["*this is plain_text text*", "*this is plain_text text*"]),
    ]
).build() its as simple as this build output

**Comment by palakagrawal22** [comment] 2024-01-03 15:51
also in context i have payload function as :  payload = Modal(
            title="label",
            callback_id="input",
            submit="Submit",
            close="Cancel",
            blocks=[
                Input(
                        block_id="id1",
                        element=PlainTextInput(action_id="action"),
                        label="example",
                        ),
                Context(
                        block_id="id2",
                        elements=[f"Note:"]
                        )
                ],
            ).build()
     return payload then output of payload ={'blocks': [{'block_id': 'id1', 'type': 'input', 'label': {'type': 'plain_text', 'text': 'example', 'emoji': True}, 'element': {'action_id': 'channel-rename-input-action', 'type': 'plain_text_input'}}, {'block_id': 'id2', 'type': 'context', 'elements': ['Note:']}], 'callback_id': 'input', 'type': 'modal', 'title': {'type': 'plain_text', 'text': 'label', 'emoji': True}, 'close': {'type': 'plain_text', 'text': 'Cancel', 'emoji': True}, 'submit': {'type': 'plain_text', 'text': 'Submit', 'emoji': True}} getting error The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/view]', '[ERROR] must provide an object [json-pointer:/view/blocks/1/elements/0]']}}

**Comment by palakagrawal22** [comment] 2024-01-09 07:12
@imryche  Can you please check?

**Comment by Kharianne** [comment] 2024-02-29 11:02
@palakagrawal22 Hi, I've encountered the same issue as you with **fields**.
The problem is that you should not pass string into the list but MarkdownText or PlainText object.
I don't know what has changed (if Slack changed something...) but according to [Slack reference](https://api.slack.com/reference/block-kit/blocks#section), fields should be an array of text objects (in this package implementation SimpleText or MarkdownText):
fields: Required if no text is provided. An array of [text objects](https://api.slack.com/reference/messaging/composition-objects#text). Any text objects included with fields will be rendered in a compact format that allows for 2 columns of side-by-side text. Maximum number of items is 10. Maximum length for the text in each item is 2000 characters.
Using simple string does not generate a text object. 
@imryche I guess that simple string should be either converted into PlainText or it should be removed as valid type. I noticed that it has been added some time before.

**Comment by imryche** [comment] 2024-03-20 10:28
Hey everyone who's encountered this issue. It should be fixed in the latest [v1.8.2](https://github.com/imryche/blockkit/releases/tag/v1.8.2) release.

**Closed by imryche** 2024-03-20 10:28 UTC
